import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // generated by FlutterFire
import 'onboarding_page.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Ensure an authenticated user exists
  await FirebaseAuth.instance.signInAnonymously();

  // Create profile doc if missing
  await _ensureProfile();

  runApp(const MyApp());
}

Future<void> _ensureProfile() async {
  final user = FirebaseAuth.instance.currentUser;
  if (user == null) return;

  final ref =
      FirebaseFirestore.instance.collection('user_profiles').doc(user.uid);
  final snap = await ref.get();
  if (snap.exists) return;

  // Simple default profile
  final uname = _genUsername();
  await ref.set({
    'displayName': uname,
    'username': uname,
    'photoURL': null,
    'createdAt': FieldValue.serverTimestamp(),
    'anon': user.isAnonymous,
    'friendUids': [],
    'prefs': {},
  });
}

String _genUsername() {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  final now = DateTime.now().microsecondsSinceEpoch;
  // cheap, deterministic-ish suffix
  final suffix = List.generate(4, (i) => chars[(now >> (i * 5)) % chars.length])
      .join();
  return 'user-$suffix';
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Task Tracker',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const OnboardingPage(),
    );
  }
}
